Public Class ObjTablavb
    Public Sub New(ByVal tabla As DataTable)
        Try

            Dim DataColumn1 As DataColumn = New DataColumn("DataColumn1")
            Dim DataColumn2 As DataColumn = New DataColumn("DataColumn2")
            Dim DataColumn3 As DataColumn = New DataColumn("DataColumn3")
            Dim DataColumn4 As DataColumn = New DataColumn("DataColumn4")
            Dim DataColumn5 As DataColumn = New DataColumn("DataColumn5")
            Dim DataColumn6 As DataColumn = New DataColumn("DataColumn6")
            Dim DataColumn7 As DataColumn = New DataColumn("DataColumn7")
            Dim DataColumn8 As DataColumn = New DataColumn("DataColumn8")
            Dim DataColumn9 As DataColumn = New DataColumn("DataColumn9")
            Dim DataColumn10 As DataColumn = New DataColumn("DataColumn10")
            Dim DataColumn11 As DataColumn = New DataColumn("DataColumn11")
            Dim DataColumn12 As DataColumn = New DataColumn("DataColumn12")
            Dim DataColumn13 As DataColumn = New DataColumn("DataColumn13")
            Dim DataColumn14 As DataColumn = New DataColumn("DataColumn14")
            Dim DataColumn15 As DataColumn = New DataColumn("DataColumn15")
            Dim DataColumn16 As DataColumn = New DataColumn("DataColumn16")
            Dim DataColumn17 As DataColumn = New DataColumn("DataColumn17")
            Dim DataColumn18 As DataColumn = New DataColumn("DataColumn18")
            Dim DataColumn19 As DataColumn = New DataColumn("DataColumn19")
            Dim DataColumn20 As DataColumn = New DataColumn("DataColumn20")
            Dim DataColumn21 As DataColumn = New DataColumn("DataColumn21")
            Dim DataColumn22 As DataColumn = New DataColumn("DataColumn22")
            Dim DataColumn23 As DataColumn = New DataColumn("DataColumn23")
            Dim DataColumn24 As DataColumn = New DataColumn("DataColumn24")
            Dim DataColumn25 As DataColumn = New DataColumn("DataColumn25")
            Dim DataColumn26 As DataColumn = New DataColumn("DataColumn26")
            Dim DataColumn27 As DataColumn = New DataColumn("DataColumn27")
            Dim DataColumn28 As DataColumn = New DataColumn("DataColumn28")
            Dim DataColumn29 As DataColumn = New DataColumn("DataColumn29")
            Dim DataColumn30 As DataColumn = New DataColumn("DataColumn30")
            Dim DataColumn31 As DataColumn = New DataColumn("DataColumn31")
            Dim DataColumn32 As DataColumn = New DataColumn("DataColumn32")
            Dim DataColumn33 As DataColumn = New DataColumn("DataColumn33")
            Dim DataColumn34 As DataColumn = New DataColumn("DataColumn34")
            Dim DataColumn35 As DataColumn = New DataColumn("DataColumn35")
            Dim DataColumn36 As DataColumn = New DataColumn("DataColumn36")
            Dim DataColumn37 As DataColumn = New DataColumn("DataColumn37")
            Dim DataColumn38 As DataColumn = New DataColumn("DataColumn38")
            Dim DataColumn39 As DataColumn = New DataColumn("DataColumn39")
            Dim DataColumn40 As DataColumn = New DataColumn("DataColumn40")
            Dim DataColumn41 As DataColumn = New DataColumn("DataColumn41")
            Dim DataColumn42 As DataColumn = New DataColumn("DataColumn42")
            Dim DataColumn43 As DataColumn = New DataColumn("DataColumn43")
            Dim DataColumn44 As DataColumn = New DataColumn("DataColumn44")
            Dim DataColumn45 As DataColumn = New DataColumn("DataColumn45")
            Dim DataColumn46 As DataColumn = New DataColumn("DataColumn46")
            Dim DataColumn47 As DataColumn = New DataColumn("DataColumn47")
            Dim DataColumn48 As DataColumn = New DataColumn("DataColumn48")
            Dim DataColumn49 As DataColumn = New DataColumn("DataColumn49")
            Dim DataColumn50 As DataColumn = New DataColumn("DataColumn50")
            Dim DataColumn51 As DataColumn = New DataColumn("DataColumn51")
            Dim DataColumn52 As DataColumn = New DataColumn("DataColumn52")
            Dim DataColumn53 As DataColumn = New DataColumn("DataColumn53")
            Dim DataColumn54 As DataColumn = New DataColumn("DataColumn54")
            Dim DataColumn55 As DataColumn = New DataColumn("DataColumn55")
            Dim DataColumn56 As DataColumn = New DataColumn("DataColumn56")
            Dim DataColumn57 As DataColumn = New DataColumn("DataColumn57")
            Dim DataColumn58 As DataColumn = New DataColumn("DataColumn58")
            Dim DataColumn59 As DataColumn = New DataColumn("DataColumn59")
            Dim DataColumn60 As DataColumn = New DataColumn("DataColumn60")
            Dim DataColumn61 As DataColumn = New DataColumn("DataColumn61")
            Dim DataColumn62 As DataColumn = New DataColumn("DataColumn62")
            Dim DataColumn63 As DataColumn = New DataColumn("DataColumn63")
            Dim DataColumn64 As DataColumn = New DataColumn("DataColumn64")
            Dim DataColumn65 As DataColumn = New DataColumn("DataColumn65")
            Dim DataColumn66 As DataColumn = New DataColumn("DataColumn66")
            Dim DataColumn67 As DataColumn = New DataColumn("DataColumn67")
            Dim DataColumn68 As DataColumn = New DataColumn("DataColumn68")
            Dim DataColumn69 As DataColumn = New DataColumn("DataColumn69")
            Dim DataColumn70 As DataColumn = New DataColumn("DataColumn70")
            Dim DataColumn71 As DataColumn = New DataColumn("DataColumn71")
            Dim DataColumn72 As DataColumn = New DataColumn("DataColumn72")
            Dim DataColumn73 As DataColumn = New DataColumn("DataColumn73")
            Dim DataColumn74 As DataColumn = New DataColumn("DataColumn74")
            Dim DataColumn75 As DataColumn = New DataColumn("DataColumn75")
            Dim DataColumn76 As DataColumn = New DataColumn("DataColumn76")
            Dim DataColumn77 As DataColumn = New DataColumn("DataColumn77")
            Dim DataColumn78 As DataColumn = New DataColumn("DataColumn78")
            Dim DataColumn79 As DataColumn = New DataColumn("DataColumn79")
            Dim DataColumn80 As DataColumn = New DataColumn("DataColumn80")
            Dim DataColumn81 As DataColumn = New DataColumn("DataColumn81")
            Dim DataColumn82 As DataColumn = New DataColumn("DataColumn82")
            Dim DataColumn83 As DataColumn = New DataColumn("DataColumn83")
            Dim DataColumn84 As DataColumn = New DataColumn("DataColumn84")
            Dim DataColumn85 As DataColumn = New DataColumn("DataColumn85")
            Dim DataColumn86 As DataColumn = New DataColumn("DataColumn86")
            Dim DataColumn87 As DataColumn = New DataColumn("DataColumn87")
            Dim DataColumn88 As DataColumn = New DataColumn("DataColumn88")
            Dim DataColumn89 As DataColumn = New DataColumn("DataColumn89")
            Dim DataColumn90 As DataColumn = New DataColumn("DataColumn90")

            DataColumn1.DataType = System.Type.GetType("System.String")
            DataColumn2.DataType = System.Type.GetType("System.String")
            DataColumn3.DataType = System.Type.GetType("System.String")
            DataColumn4.DataType = System.Type.GetType("System.String")
            DataColumn5.DataType = System.Type.GetType("System.String")
            DataColumn6.DataType = System.Type.GetType("System.String")
            DataColumn7.DataType = System.Type.GetType("System.String")
            DataColumn8.DataType = System.Type.GetType("System.String")
            DataColumn9.DataType = System.Type.GetType("System.String")
            DataColumn10.DataType = System.Type.GetType("System.String")
            DataColumn11.DataType = System.Type.GetType("System.String")
            DataColumn12.DataType = System.Type.GetType("System.String")
            DataColumn13.DataType = System.Type.GetType("System.String")
            DataColumn14.DataType = System.Type.GetType("System.String")
            DataColumn15.DataType = System.Type.GetType("System.String")
            DataColumn16.DataType = System.Type.GetType("System.String")
            DataColumn17.DataType = System.Type.GetType("System.String")
            DataColumn18.DataType = System.Type.GetType("System.String")
            DataColumn19.DataType = System.Type.GetType("System.String")
            DataColumn20.DataType = System.Type.GetType("System.String")
            DataColumn21.DataType = System.Type.GetType("System.String")
            DataColumn22.DataType = System.Type.GetType("System.String")
            DataColumn23.DataType = System.Type.GetType("System.String")
            DataColumn24.DataType = System.Type.GetType("System.String")
            DataColumn25.DataType = System.Type.GetType("System.String")
            DataColumn26.DataType = System.Type.GetType("System.String")
            DataColumn27.DataType = System.Type.GetType("System.String")
            DataColumn28.DataType = System.Type.GetType("System.String")
            DataColumn29.DataType = System.Type.GetType("System.String")
            DataColumn30.DataType = System.Type.GetType("System.String")
            DataColumn31.DataType = System.Type.GetType("System.String")
            DataColumn32.DataType = System.Type.GetType("System.String")
            DataColumn33.DataType = System.Type.GetType("System.String")
            DataColumn34.DataType = System.Type.GetType("System.String")
            DataColumn35.DataType = System.Type.GetType("System.String")
            DataColumn36.DataType = System.Type.GetType("System.String")
            DataColumn37.DataType = System.Type.GetType("System.String")
            DataColumn38.DataType = System.Type.GetType("System.String")
            DataColumn39.DataType = System.Type.GetType("System.String")
            DataColumn40.DataType = System.Type.GetType("System.String")
            DataColumn41.DataType = System.Type.GetType("System.String")
            DataColumn42.DataType = System.Type.GetType("System.String")
            DataColumn43.DataType = System.Type.GetType("System.String")
            DataColumn44.DataType = System.Type.GetType("System.String")
            DataColumn45.DataType = System.Type.GetType("System.String")
            DataColumn46.DataType = System.Type.GetType("System.String")
            DataColumn47.DataType = System.Type.GetType("System.String")
            DataColumn48.DataType = System.Type.GetType("System.String")
            DataColumn49.DataType = System.Type.GetType("System.String")
            DataColumn50.DataType = System.Type.GetType("System.String")
            DataColumn51.DataType = System.Type.GetType("System.String")
            DataColumn52.DataType = System.Type.GetType("System.String")
            DataColumn53.DataType = System.Type.GetType("System.String")
            DataColumn54.DataType = System.Type.GetType("System.String")
            DataColumn55.DataType = System.Type.GetType("System.String")
            DataColumn56.DataType = System.Type.GetType("System.String")
            DataColumn57.DataType = System.Type.GetType("System.String")
            DataColumn58.DataType = System.Type.GetType("System.String")
            DataColumn59.DataType = System.Type.GetType("System.String")
            DataColumn60.DataType = System.Type.GetType("System.String")
            DataColumn61.DataType = System.Type.GetType("System.String")
            DataColumn62.DataType = System.Type.GetType("System.String")
            DataColumn63.DataType = System.Type.GetType("System.String")
            DataColumn64.DataType = System.Type.GetType("System.String")
            DataColumn65.DataType = System.Type.GetType("System.String")
            DataColumn66.DataType = System.Type.GetType("System.String")
            DataColumn67.DataType = System.Type.GetType("System.String")
            DataColumn68.DataType = System.Type.GetType("System.String")
            DataColumn69.DataType = System.Type.GetType("System.String")
            DataColumn70.DataType = System.Type.GetType("System.String")
            DataColumn71.DataType = System.Type.GetType("System.String")
            DataColumn72.DataType = System.Type.GetType("System.String")
            DataColumn73.DataType = System.Type.GetType("System.String")
            DataColumn74.DataType = System.Type.GetType("System.String")
            DataColumn75.DataType = System.Type.GetType("System.String")
            DataColumn76.DataType = System.Type.GetType("System.String")
            DataColumn77.DataType = System.Type.GetType("System.String")
            DataColumn78.DataType = System.Type.GetType("System.String")
            DataColumn79.DataType = System.Type.GetType("System.String")
            DataColumn80.DataType = System.Type.GetType("System.String")
            DataColumn81.DataType = System.Type.GetType("System.String")
            DataColumn82.DataType = System.Type.GetType("System.String")
            DataColumn83.DataType = System.Type.GetType("System.String")
            DataColumn84.DataType = System.Type.GetType("System.String")
            DataColumn85.DataType = System.Type.GetType("System.String")
            DataColumn86.DataType = System.Type.GetType("System.String")
            DataColumn87.DataType = System.Type.GetType("System.String")
            DataColumn88.DataType = System.Type.GetType("System.String")
            DataColumn89.DataType = System.Type.GetType("System.String")
            DataColumn90.DataType = System.Type.GetType("System.String")

            tabla.Columns.Add(DataColumn1)
            tabla.Columns.Add(DataColumn2)
            tabla.Columns.Add(DataColumn3)
            tabla.Columns.Add(DataColumn4)
            tabla.Columns.Add(DataColumn5)
            tabla.Columns.Add(DataColumn6)
            tabla.Columns.Add(DataColumn7)
            tabla.Columns.Add(DataColumn8)
            tabla.Columns.Add(DataColumn9)
            tabla.Columns.Add(DataColumn10)
            tabla.Columns.Add(DataColumn11)
            tabla.Columns.Add(DataColumn12)
            tabla.Columns.Add(DataColumn13)
            tabla.Columns.Add(DataColumn14)
            tabla.Columns.Add(DataColumn15)
            tabla.Columns.Add(DataColumn16)
            tabla.Columns.Add(DataColumn17)
            tabla.Columns.Add(DataColumn18)
            tabla.Columns.Add(DataColumn19)
            tabla.Columns.Add(DataColumn20)
            tabla.Columns.Add(DataColumn21)
            tabla.Columns.Add(DataColumn22)
            tabla.Columns.Add(DataColumn23)
            tabla.Columns.Add(DataColumn24)
            tabla.Columns.Add(DataColumn25)
            tabla.Columns.Add(DataColumn26)
            tabla.Columns.Add(DataColumn27)
            tabla.Columns.Add(DataColumn28)
            tabla.Columns.Add(DataColumn29)
            tabla.Columns.Add(DataColumn30)
            tabla.Columns.Add(DataColumn31)
            tabla.Columns.Add(DataColumn32)
            tabla.Columns.Add(DataColumn33)
            tabla.Columns.Add(DataColumn34)
            tabla.Columns.Add(DataColumn35)
            tabla.Columns.Add(DataColumn36)
            tabla.Columns.Add(DataColumn37)
            tabla.Columns.Add(DataColumn38)
            tabla.Columns.Add(DataColumn39)
            tabla.Columns.Add(DataColumn40)
            tabla.Columns.Add(DataColumn41)
            tabla.Columns.Add(DataColumn42)
            tabla.Columns.Add(DataColumn43)
            tabla.Columns.Add(DataColumn44)
            tabla.Columns.Add(DataColumn45)
            tabla.Columns.Add(DataColumn46)
            tabla.Columns.Add(DataColumn47)
            tabla.Columns.Add(DataColumn48)
            tabla.Columns.Add(DataColumn49)
            tabla.Columns.Add(DataColumn50)
            tabla.Columns.Add(DataColumn51)
            tabla.Columns.Add(DataColumn52)
            tabla.Columns.Add(DataColumn53)
            tabla.Columns.Add(DataColumn54)
            tabla.Columns.Add(DataColumn55)
            tabla.Columns.Add(DataColumn56)
            tabla.Columns.Add(DataColumn57)
            tabla.Columns.Add(DataColumn58)
            tabla.Columns.Add(DataColumn59)
            tabla.Columns.Add(DataColumn60)
            tabla.Columns.Add(DataColumn61)
            tabla.Columns.Add(DataColumn62)
            tabla.Columns.Add(DataColumn63)
            tabla.Columns.Add(DataColumn64)
            tabla.Columns.Add(DataColumn65)
            tabla.Columns.Add(DataColumn66)
            tabla.Columns.Add(DataColumn67)
            tabla.Columns.Add(DataColumn68)
            tabla.Columns.Add(DataColumn69)
            tabla.Columns.Add(DataColumn70)
            tabla.Columns.Add(DataColumn71)
            tabla.Columns.Add(DataColumn72)
            tabla.Columns.Add(DataColumn73)
            tabla.Columns.Add(DataColumn74)
            tabla.Columns.Add(DataColumn75)
            tabla.Columns.Add(DataColumn76)
            tabla.Columns.Add(DataColumn77)
            tabla.Columns.Add(DataColumn78)
            tabla.Columns.Add(DataColumn79)
            tabla.Columns.Add(DataColumn80)
            tabla.Columns.Add(DataColumn81)
            tabla.Columns.Add(DataColumn82)
            tabla.Columns.Add(DataColumn83)
            tabla.Columns.Add(DataColumn84)
            tabla.Columns.Add(DataColumn85)
            tabla.Columns.Add(DataColumn86)
            tabla.Columns.Add(DataColumn87)
            tabla.Columns.Add(DataColumn88)
            tabla.Columns.Add(DataColumn89)
            tabla.Columns.Add(DataColumn90)

        Catch ex As Exception
            MsgBox(Err.Description & vbCrLf & "CLASE: " & "objTabla" & vbCrLf & _
           "METODO: " & "Constructor")
        End Try
    End Sub
End Class
